name: Build and Publish for Apple Silicon

on:
    push:
      branches:
        - main
    pull_request:
      types:
        - closed

jobs:
  build_wheels_macos:
    name: Build wheels on macos-11
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.0
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
          
  upload_pypi:
    needs: build_wheels_macos
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist/

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install twine
        run: python -m pip install twine

      - name: Publish wheels to PyPI
        run: twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ dist/*.whl
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
