name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install setuptools
        run: python -m pip install --upgrade setuptools wheel twine

      - name: Build wheel
        run: python setup.py bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.whl

  upload_wheels:
    needs: build_wheels
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: dist/
          
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.TEST_PYPI_USERNAME }}
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: dist/
