name: Build and Publish Source Distribution

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - closed

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build sdist
        run: |
          pip install wheel
          python setup.py sdist
          mkdir -p dists
          mv dist/*.tar.gz dists/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: ./dists/*.tar.gz

  upload_sdist:
    needs: build_sdist
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - name: Download sdist
        uses: actions/download-artifact@v2
        with:
          name: sdist
          path: dist/

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install twine
        run: python -m pip install twine

      - name: Publish sdist to PyPI
        run: |
          if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*.tar.gz
          else
            twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ dist/*.tar.gz
          fi
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
