name: Build and Publish Linux

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build_wheels:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install build dependencies
        run: python -m pip install build

      - name: Build wheel
        run: python -m build --wheel

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheels-ubuntu
          path: dist/*.whl

  build_sdist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install build dependencies
        run: python -m pip install build

      - name: Build sdist
        run: python -m build --sdist

      - uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels-ubuntu
          path: dist

      - uses: actions/download-artifact@v2
        with:
          name: sdist
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}